version: '3.7'

volumes:
  mysql_data:

services:
  db:
    container_name: sqs_db
    image: mysql:latest
    environment:
      MYSQL_DATABASE: data
      MYSQL_USER: root
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  backend:
    restart: unless-stopped
    container_name: sqs_backend
    image: ghcr.io/lmaistud/sqs/sqs_backend:latest
    build:
      context: ./backend
      dockerfile: src/main/java/com/sqs_maier/docker/Dockerfile.jvm
    ports:
      - "8080:8080"
    depends_on:
      - db

  frontend:
    restart: unless-stopped
    container_name: sqs_frontend
    image: ghcr.io/lmaistud/sqs/sqs_frontend:latest
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      - backend

