name: Run Playwright Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Install Playwright
        run: npm install -g playwright

      - name: Run Playwright Tests
        run: |
          cd frontend
          cd src
          cd tests
          playwright test tests
